name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Deploy to github pages
        run: |
          git config user.name lnwu
          git config user.email wind2729@gmail.com
          yarn && yarn deploy
